apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: ns-team-1-env-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jpt-test
    spec:
      containers:
        - name: jpt-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              hostPort: 8083
              protocol: TCP