apiVersion: v1
kind: Service
metadata:
  name: jpt-test
  namespace: ns-team-1-env-2
spec:
  ports:
  - name: http-p-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jpt-test